version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    container_name: db_test_case_go
    restart: always
    expose:
      - "5432"
    ports:
      - "5434:5432"
    env_file:
      - .env