"""add column to rack is_primary

Revision ID: 4bf6b91d207e
Revises: 59a47bcfc905
Create Date: 2024-02-22 09:41:03.788605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bf6b91d207e"
down_revision: Union[str, None] = "59a47bcfc905"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assemblies")
    op.add_column(
        "product_rack_association",
        sa.Column("is_primary", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_rack_association", "is_primary")
    op.create_table(
        "assemblies",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "title", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="assemblies_pkey"),
        sa.UniqueConstraint("title", name="assemblies_title_key"),
    )
    # ### end Alembic commands ###
