"""Create racks, orders, assmblies tables without relatins

Revision ID: ea869e93cba4
Revises: b0e78da2bd3f
Create Date: 2024-02-21 10:45:23.496217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea869e93cba4"
down_revision: Union[str, None] = "b0e78da2bd3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
